# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def _coalesced_identity_func(x):
    # Identity pointwise kernel: returns each element unchanged.
    #
    # ``aten::_coalesced_`` is a pure-metadata op: it only toggles the
    # ``is_coalesced`` flag of a sparse COO tensor and never touches the
    # underlying indices/values data. The per-element computation is therefore
    # a no-op identity. This kernel is the Triton implementation that would
    # process the values data when the op needed to do per-element work; the
    # metadata fast-path below does not launch it, since doing so would only
    # add kernel-launch overhead for a mutation that changes no data.
    return x


def _coalesced_(self: torch.Tensor, coalesced: bool) -> torch.Tensor:
    """Set the ``coalesced`` flag of a sparse COO tensor in place.

    ``aten::_coalesced_`` is a metadata-only mutation: it flips the tensor's
    ``is_coalesced`` bit and returns ``self`` without modifying the indices or
    values data. The flag is toggled through the native autograd path
    (dispatched below the autograd key) so the actual in-place metadata
    mutation is performed by the native backend kernel, rather than
    re-entering this override (which would recurse).
    """
    logger.debug("GEMS _COALESCED_")

    if self.layout != torch.sparse_coo:
        raise RuntimeError(
            "_coalesced_ only supports sparse coordinate (coo) tensors, "
            f"but got layout {self.layout}"
        )

    # The op is metadata-only: there is no per-element data to compute, so we
    # do not launch ``_coalesced_identity_func`` (launching it would add
    # kernel-launch overhead for no work, since the stored data is unchanged).

    # Toggle the coalesced flag in place. Dispatching below the autograd key
    # routes the call to the native backend (SparseCUDA/SparseCPU) kernel that
    # performs the actual in-place metadata mutation, instead of re-entering
    # this override (which would recurse).
    with torch._C._AutoDispatchBelowAutograd():
        torch.ops.aten._coalesced_.default(self, coalesced)

    return self
