# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

# Number of values kept per group of 4 under 2:4 structured sparsity.
NNZ_PER_GROUP = 2
GROUP_SIZE = 4


@libentry()
@triton.jit
def _cslt_compress_kernel(
    input_ptr,
    output_ptr,
    M,
    N,
    N_GROUPS,  # N // 4  -- number of 2:4 groups per row
    N_PACKED,  # N // 2  -- packed non-zero count per row
    stride_im,
    stride_in,
    stride_om,
    stride_on,
    GROUP_SIZE: tl.constexpr,
    NNZ_PER_GROUP: tl.constexpr,
    N_GROUPS_IN_TILE: tl.constexpr,  # BLOCK_N // GROUP_SIZE
    BLOCK_N: tl.constexpr,
):
    """Compress a 2:4 structured-sparse matrix into (packed-values | per-group meta).

    The output tensor has shape ``(M, N_PACKED + N_GROUPS)``. For every row ``r``:
      * ``output[r, 0 : N_PACKED]`` holds the ``N/2`` surviving values, two per
        group, written in the order the non-zero positions appear within each
        consecutive group of 4.
      * ``output[r, N_PACKED : N_PACKED + N_GROUPS]`` holds the 2:4 pattern code
        (a float in ``[0, 5]``) for each group.

    One program is launched per row. The row is processed in tiles of
    ``BLOCK_N`` columns (a multiple of 4 so it always covers whole groups).
    """
    row = tl.program_id(0)
    if row >= M:
        return

    in_row_ptr = input_ptr + row * stride_im
    out_row_ptr = output_ptr + row * stride_om

    # Packed-value write cursor and group cursor, advanced together across tiles.
    packed_cursor = 0
    group_cursor = 0

    num_tiles = tl.cdiv(N, BLOCK_N)
    for t in range(num_tiles):
        col_start = t * BLOCK_N
        g_idx = tl.arange(0, N_GROUPS_IN_TILE)
        # Base column index of the first position of each group in this tile.
        group_col = col_start + g_idx * GROUP_SIZE

        # Load the four per-group positions as separate vectors to avoid constant
        # tensor indexing (unsupported in Triton). v{k}[g] == vals[group_col[g] + k].
        v0 = tl.load(
            in_row_ptr + (group_col + 0) * stride_in,
            mask=(group_col + 0) < N,
            other=0.0,
        )
        v1 = tl.load(
            in_row_ptr + (group_col + 1) * stride_in,
            mask=(group_col + 1) < N,
            other=0.0,
        )
        v2 = tl.load(
            in_row_ptr + (group_col + 2) * stride_in,
            mask=(group_col + 2) < N,
            other=0.0,
        )
        v3 = tl.load(
            in_row_ptr + (group_col + 3) * stride_in,
            mask=(group_col + 3) < N,
            other=0.0,
        )

        nz0 = v0 != 0
        nz1 = v1 != 0
        nz2 = v2 != 0
        nz3 = v3 != 0
        # Raw 4-bit mask per group: b0*1 + b1*2 + b2*4 + b3*8.
        raw_code = (
            nz0.to(tl.int32) * 1
            + nz1.to(tl.int32) * 2
            + nz2.to(tl.int32) * 4
            + nz3.to(tl.int32) * 8
        )
        # Map the six valid masks onto the canonical code in [0, 5].
        meta_code = tl.where(
            raw_code == 3,
            0,
            tl.where(
                raw_code == 5,
                1,
                tl.where(
                    raw_code == 6,
                    2,
                    tl.where(raw_code == 9, 3, tl.where(raw_code == 10, 4, 5)),
                ),
            ),
        )

        # First/second surviving value per group, in source position order.
        first_val = tl.where(nz0, v0, tl.where(nz1, v1, tl.where(nz2, v2, v3)))
        second_val = tl.where(nz3, v3, tl.where(nz2, v2, tl.where(nz1, v1, v0)))

        # Pack the two values consecutively into the packed-value region.
        pack_offs = packed_cursor + g_idx * NNZ_PER_GROUP
        p0 = pack_offs + 0
        p1 = pack_offs + 1
        pack_mask = p0 < N_PACKED
        tl.store(out_row_ptr + p0 * stride_on, first_val, mask=pack_mask)
        tl.store(
            out_row_ptr + p1 * stride_on, second_val, mask=pack_mask & (p1 < N_PACKED)
        )

        # Store per-group metadata code into the meta region.
        meta_offs = N_PACKED + group_cursor + g_idx
        meta_mask = (group_cursor + g_idx) < N_GROUPS
        tl.store(
            out_row_ptr + meta_offs * stride_on,
            meta_code.to(tl.float32),
            mask=meta_mask,
        )

        packed_cursor = packed_cursor + N_GROUPS_IN_TILE * NNZ_PER_GROUP
        group_cursor = group_cursor + N_GROUPS_IN_TILE


def _cslt_compress(input: torch.Tensor) -> torch.Tensor:
    """Compress a 2:4 structured-sparse matrix into packed values + metadata.

    Args:
        input: A 2-D tensor of shape ``(M, N)`` satisfying 2:4 structured sparsity,
            i.e. for every group of ``4`` consecutive elements along the last
            dimension exactly ``2`` are non-zero. ``N`` must be a positive multiple
            of ``4``.

    Returns:
        A tensor of shape ``(M, N_PACKED + N_GROUPS)`` where ``N_PACKED = N // 2``
        and ``N_GROUPS = N // 4``. Columns ``[0, N_PACKED)`` hold the surviving
        values per row (two per group, in source order); columns
        ``[N_PACKED, N_PACKED + N_GROUPS)`` hold the 2:4 pattern code (a float in
        ``[0, 5]``) for each group.
    """
    logger.debug("GEMS _CSLT_COMPRESS")
    if input.dim() != 2:
        raise ValueError(
            "_cslt_compress expects a 2-D tensor, got shape %r" % (tuple(input.shape),)
        )
    M, N = input.shape
    if N % GROUP_SIZE != 0:
        raise ValueError(
            "_cslt_compress expects the last dimension to be a multiple of 4, got %d"
            % N
        )
    N_GROUPS = N // GROUP_SIZE
    N_PACKED = N_GROUPS * NNZ_PER_GROUP
    out_cols = N_PACKED + N_GROUPS
    if M == 0 or N == 0:
        return torch.empty((M, out_cols), dtype=input.dtype, device=input.device)

    out = torch.empty((M, out_cols), dtype=input.dtype, device=input.device)

    # BLOCK_N must be a multiple of GROUP_SIZE so each tile covers whole groups.
    BLOCK_N = triton.next_power_of_2(N) if N <= 4096 else 4096
    BLOCK_N = max(BLOCK_N, GROUP_SIZE)
    N_GROUPS_IN_TILE = BLOCK_N // GROUP_SIZE
    grid = (M,)
    _cslt_compress_kernel[grid](
        input,
        out,
        M,
        N,
        N_GROUPS,
        N_PACKED,
        input.stride(0),
        input.stride(1),
        out.stride(0),
        out.stride(1),
        GROUP_SIZE=GROUP_SIZE,
        NNZ_PER_GROUP=NNZ_PER_GROUP,
        N_GROUPS_IN_TILE=N_GROUPS_IN_TILE,
        BLOCK_N=BLOCK_N,
    )
    return out
