# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def _cslt_sparse_mm_search(
    compressed_A,
    dense_B,
    bias=None,
    alpha=None,
    out_dtype=None,
    transpose_result=False,
):
    """FlagGems implementation of ``_cslt_sparse_mm_search``.

    Returns a cuSPARSELt matmul algorithm id (a Python ``int``) selected for the
    given compressed (2:4 structured sparse) matrix ``compressed_A`` and dense
    matrix ``dense_B``. The returned id can be passed as ``alg_id`` to
    ``torch._cslt_sparse_mm``.

    This is a meta operator with no numeric computation to reimplement: the
    only work is querying cuSPARSELt for a suitable algorithm id, which is
    delegated to ``torch._C._cusparselt.mm_search``. The lower-level entry point
    is used instead of the public ``aten`` ``_cslt_sparse_mm_search`` to avoid
    infinite recursion: once this op is registered, the public op redispatches
    back into this implementation.
    """
    logger.debug("GEMS _CSLT_SPARSE_MM_SEARCH")

    if not compressed_A.is_cuda:
        raise RuntimeError("_cslt_sparse_mm_search expects CUDA inputs")

    # ``mm_search`` returns a 4-tuple of ints; the first element is the
    # algorithm id, matching the single-int return value of the aten op.
    alg_id, _, _, _ = torch._C._cusparselt.mm_search(
        compressed_A,
        dense_B,
        bias,
        alpha,
        out_dtype,
        transpose_result,
    )
    return alg_id
