# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import builtins
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


def _torch_dtype_to_triton(dtype: torch.dtype):
    if dtype == torch.float16:
        return tl.float16
    if dtype == torch.bfloat16:
        return tl.bfloat16
    if dtype == torch.float32:
        return tl.float32
    if dtype == torch.float64:
        return tl.float64
    raise ValueError(f"Unsupported dtype for Triton conversion: {dtype}")


@libentry()
@triton.jit
def histogramdd_col_minmax_kernel(
    inp_ptr,
    min_out_ptr,
    max_out_ptr,
    nonfinite_out_ptr,
    M,
    N,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    ACC_DTYPE: tl.constexpr,
    OUT_DTYPE: tl.constexpr,
):
    """Compute the per-column (per-dimension) min and max of a 2-D input.

    ``inp`` is interpreted as a contiguous ``(M, N)`` matrix where ``M`` is the
    number of points and ``N`` is the number of dimensions. Each program handles
    ``BLOCK_N`` columns and reduces all ``M`` rows, writing one min/max pair per
    column into ``min_out`` / ``max_out`` (both of size ``N``). A per-column
    flag (1 = at least one non-finite value was seen) is also written to
    ``nonfinite_out_ptr`` so the caller can replicate torch's "range is not
    finite" check without a second pass over the data.
    """
    pid = ext.program_id(0)
    cols = pid * BLOCK_N + tl.arange(0, BLOCK_N)
    col_mask = cols < N

    # histogramdd is only supported for floating-point dtypes, so the
    # identity elements are +/- inf expressed in the accumulator dtype.
    _min = tl.full([BLOCK_N], value=float("inf"), dtype=ACC_DTYPE)
    _max = tl.full([BLOCK_N], value=float("-inf"), dtype=ACC_DTYPE)
    _nonfinite = tl.full([BLOCK_N], value=0, dtype=tl.int32)
    _has_nan = tl.full([BLOCK_N], value=0, dtype=tl.int32)

    for off in range(0, M, BLOCK_M):
        rows = off + tl.arange(0, BLOCK_M)[:, None]
        row_mask = rows < M
        mask = row_mask & col_mask[None, :]
        a = tl.load(inp_ptr + rows * N + cols[None, :], mask=mask, other=0.0)
        a = a.to(ACC_DTYPE)
        # Track whether this block saw any non-finite value (NaN/inf) per column.
        _nonfinite = _nonfinite | tl.sum(
            (a != a) | (a == float("inf")) | (a == float("-inf")), axis=0
        ).to(tl.int32)
        # Track NaN separately so the stored min/max can propagate it the way
        # torch's reductions do. This lets the caller build the "range is not
        # finite" message from these outputs alone, with no second pass over the
        # input and no host-side col.min()/col.max().
        _has_nan = _has_nan | tl.sum((a != a).to(tl.int32), axis=0)
        # Replace masked-out entries with identity elements so that the
        # reductions ignore them: +inf for min, -inf for max.
        a_min = tl.where(mask, a, float("inf"))
        a_max = tl.where(mask, a, float("-inf"))
        _min = tl.minimum(_min, tl.min(a_min, axis=0))
        _max = tl.maximum(_max, tl.max(a_max, axis=0))

    # Propagate NaN into min/max like torch's reductions, so a column containing
    # NaN reports nan rather than the min/max of its finite values.
    nan_val = float("nan")
    _min = tl.where(_has_nan != 0, nan_val, _min)
    _max = tl.where(_has_nan != 0, nan_val, _max)
    tl.store(min_out_ptr + cols, _min.to(OUT_DTYPE), mask=col_mask)
    tl.store(max_out_ptr + cols, _max.to(OUT_DTYPE), mask=col_mask)
    tl.store(nonfinite_out_ptr + cols, _nonfinite, mask=col_mask)


@libentry()
@triton.jit
def histogramdd_linspace_kernel(
    out_ptr,
    start,
    end,
    step,
    steps,
    BLOCK_SIZE: tl.constexpr,
):
    """Write ``steps`` evenly spaced values between ``start`` and ``end``.

    Mirrors ``torch.linspace``: for ``steps == 1`` only ``start`` is produced
    (handled by the caller); for ``steps >= 2`` the value at index ``i`` is
    ``start + step * i`` with ``step = (end - start) / (steps - 1)``.
    """
    pid = ext.program_id(0)
    idx = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = idx < steps
    val = start + step * idx
    tl.store(out_ptr + idx, val, mask=mask)


@libentry()
@triton.jit
def histogramdd_linspace_from_tensor_kernel(
    out_ptr,
    min_ptr,
    max_ptr,
    d,
    steps,
    inv_denom,
    BLOCK_SIZE: tl.constexpr,
):
    """Device-side linspace whose endpoints are read from ``min_ptr``/``max_ptr``.

    Same value formula as ``histogramdd_linspace_kernel``, but the endpoints stay
    on the device: they are loaded from column ``d`` of the min/max reduction
    outputs rather than passed as host scalars. This keeps the data-derived path
    free of ``.item()``/``.tolist()`` synchronisation, so it is safe under graph
    capture. Degenerate columns (min == max) are widened to a unit interval here,
    matching the host path.
    """
    # Match torch.linspace, which computes in the output dtype: accumulating in
    # fp64 for an fp32 output shifts interior edges by ~1 ulp versus ATen.
    lo = tl.load(min_ptr + d)
    hi = tl.load(max_ptr + d)
    # Widen a degenerate range exactly as the host path does.
    degenerate = lo == hi
    lo = tl.where(degenerate, lo - 0.5, lo)
    hi = tl.where(degenerate, hi + 0.5, hi)
    # ``inv_denom`` is 1/(steps-1), computed on the host so this stays a multiply
    # (``steps`` is a runtime arg, not a constexpr, so it cannot be used in Python
    # arithmetic here).
    step = (hi - lo) * inv_denom

    pid = ext.program_id(0)
    idx = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = idx < steps
    val = lo + step * idx.to(lo.dtype)
    # The final edge is pinned to the exact endpoint, as torch.linspace does, so
    # accumulated rounding cannot push it past the data maximum. Guarded on
    # steps > 1: with a single edge, index 0 is both first and last and must stay
    # at the (widened) low endpoint.
    val = tl.where((steps > 1) & (idx == steps - 1), hi, val)
    tl.store(out_ptr + idx, val, mask=mask)


def _is_capturing(device):
    """True while a CUDA graph is being captured on ``device``'s stream.

    Used to skip the one host-side read on the data-derived path, which cannot be
    performed during capture. Returns False on backends without graph support.
    """
    try:
        return torch.cuda.is_available() and torch.cuda.is_current_stream_capturing()
    except (AttributeError, RuntimeError):
        return False


def _linspace_from_tensor(col_min, col_max, d, steps, dtype, device):
    """Build the edges for dimension ``d`` without reading min/max on the host."""
    out = torch.empty((steps,), dtype=dtype, device=device)
    if steps <= 0:
        return out
    BLOCK_SIZE = triton.next_power_of_2(steps) if steps > 1 else 1
    BLOCK_SIZE = builtins.min(BLOCK_SIZE, 1024)
    grid = (triton.cdiv(steps, BLOCK_SIZE),)
    with torch_device_fn.device(device):
        histogramdd_linspace_from_tensor_kernel[grid](
            out,
            col_min,
            col_max,
            d,
            steps,
            1.0 / (steps - 1) if steps > 1 else 0.0,
            BLOCK_SIZE=BLOCK_SIZE,
        )
    return out


def _compute_col_minmax(inp, N):
    """Return (min_per_col, max_per_col, nonfinite_per_col) for the ``(M, N)`` input.

    ``nonfinite_per_col[d]`` is 1 iff column ``d`` contained at least one
    NaN/inf value, which lets the caller reproduce torch's "range is not
    finite" check without a second pass over the (potentially large) input.
    """
    M = inp.numel() // N
    dtype = inp.dtype
    min_out = torch.empty((N,), dtype=dtype, device=inp.device)
    max_out = torch.empty((N,), dtype=dtype, device=inp.device)
    nonfinite_out = torch.zeros((N,), dtype=torch.int32, device=inp.device)

    BLOCK_N = triton.next_power_of_2(N) if N > 0 else 1
    BLOCK_M = 1024
    # Accumulate in fp32 for everything but fp64 (which keeps full precision),
    # matching the behaviour of PyTorch's CPU min/max reductions.
    acc_dtype = tl.float64 if dtype == torch.float64 else tl.float32
    out_dtype = _torch_dtype_to_triton(dtype)
    grid = (triton.cdiv(N, BLOCK_N),)
    with torch_device_fn.device(inp.device):
        histogramdd_col_minmax_kernel[grid](
            inp,
            min_out,
            max_out,
            nonfinite_out,
            M,
            N,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            ACC_DTYPE=acc_dtype,
            OUT_DTYPE=out_dtype,
        )
    return min_out, max_out, nonfinite_out


def _linspace(start, end, steps, dtype, device):
    """Build a 1-D tensor of ``steps`` values linearly spaced from start to end.

    The computation is done by a Triton kernel for steps >= 2; steps == 1
    returns a single-element tensor holding ``start``.
    """
    out = torch.empty((steps,), dtype=dtype, device=device)
    if steps <= 0:
        return out
    if steps == 1:
        out.fill_(start)
        return out
    step = (float(end) - float(start)) / (steps - 1)
    # Each program writes a contiguous chunk of the 1-D edge tensor; 1024 is a
    # safe power-of-two tile that amortizes launch overhead for typical bin counts.
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(steps, BLOCK_SIZE),)
    with torch_device_fn.device(device):
        histogramdd_linspace_kernel[grid](
            out, float(start), float(end), step, steps, BLOCK_SIZE=BLOCK_SIZE
        )
    return out


def _histogramdd_bin_edges_impl(
    self, bins, *, range=None, weight=None, density=False, out=None
):
    if self.dim() < 2:
        raise RuntimeError(
            "torch.histogramdd: input tensor should have at least 2 dimensions"
        )

    N = self.shape[-1]
    if len(bins) != N:
        raise RuntimeError(
            "histogramdd: The size of bins must be equal to the innermost dimension of the input."
        )

    # ``range`` shadows the built-in; keep the original name for the public API
    # but use ``range_`` locally and the built-in via ``builtins.range``.
    range_ = range
    range = builtins.range

    if range_ is not None:
        if len(range_) != 2 * N:
            raise RuntimeError(
                f"torch.histogramdd: for a {N}-dimensional histogram range "
                f"should have {2 * N} elements, but got {len(range_)}"
            )
        ranges = [(float(range_[2 * d]), float(range_[2 * d + 1])) for d in range(N)]
        # ATen rejects a non-finite explicit range up front, with the same wording
        # it uses for a non-finite data range. Without this the edges themselves
        # come back non-finite instead of raising.
        for d in range(N):
            lo, hi = ranges[d]
            if not (math.isfinite(lo) and math.isfinite(hi)):
                raise RuntimeError(
                    f"torch.histogramdd: dimension {d}'s range "
                    f"[{lo:g}, {hi:g}] is not finite"
                )
    else:
        ranges = [None] * N

    # An empty innermost dimension means there are no histogram dimensions at all,
    # so there are no edges to produce. Handled before the reshape below because
    # reshape(-1, 0) cannot infer the leading extent.
    if N == 0:
        return () if out is None else out

    # Flatten all leading dimensions so input becomes (M, N) C-contiguous.
    inp2d = self.reshape(-1, N).contiguous()

    col_min = col_max = None
    if range_ is None:
        # PyTorch falls back to a [0, 1] range when the input has no points, so
        # the per-column reduction is only meaningful when there is data.
        if inp2d.shape[0] == 0:
            empty_min_max = (0.0, 1.0)
        else:
            empty_min_max = None
            col_min, col_max, nonfinite = _compute_col_minmax(inp2d, N)
            # torch's histogramdd raises when a dimension's range is non-finite.
            # Deciding to raise is inherently a host-side branch, so it needs the
            # flag's value; the min/max values themselves stay on the device and are
            # consumed by histogramdd_linspace_from_tensor_kernel (no second pass
            # over the input, no host col.min()/col.max()).
            #
            # The read is skipped while a graph is capturing: an exception cannot be
            # raised from a replay anyway, and reading here would break capture. Eager
            # execution keeps full error parity with ATen; under capture the edges are
            # computed from the propagated NaN instead, which is what the recorded
            # kernels would produce.
            if not _is_capturing(inp2d.device):
                nonfinite_list = nonfinite.tolist()
                if any(nonfinite_list):
                    # The kernel stores a per-column count, so test for non-zero.
                    bad_d = next(i for i, v in enumerate(nonfinite_list) if v)
                    lo, hi = col_min[bad_d].item(), col_max[bad_d].item()
                    raise RuntimeError(
                        f"torch.histogramdd: dimension {bad_d}'s range "
                        f"[{lo:g}, {hi:g}] is not finite"
                    )

    edges = []
    for d in range(N):
        nb = int(bins[d])
        num_edges = nb + 1
        # ATen builds the edges with linspace(steps=bins+1), so bins == -1 (zero
        # steps) and bins == 0 (one step) are both legal and only bins <= -2 is
        # rejected -- by linspace itself, with this message. Clamping the negative
        # count to zero instead would silently accept those inputs.
        if num_edges < 0:
            raise RuntimeError("number of steps must be non-negative")

        if range_ is not None:
            left, right = ranges[d]
            if left > right:
                raise RuntimeError(
                    f"torch.histogramdd: min should not exceed max, but got "
                    f"min {left} max {right} for dimension {d}"
                )
        elif empty_min_max is None:
            # Data-derived endpoints stay on the device: the linspace kernel reads
            # column d of col_min/col_max itself (including the degenerate-range
            # widening), so nothing is materialised on the host here. Finiteness was
            # already validated above.
            edges.append(
                _linspace_from_tensor(
                    col_min, col_max, d, num_edges, self.dtype, self.device
                )
            )
            continue
        else:
            left, right = empty_min_max

        # When the data (or explicit range) is degenerate (min == max), PyTorch
        # widens the range to a unit interval centred on the value.
        if left == right:
            # Widening happens before the edge count is considered, so a single
            # edge is the *widened* left endpoint: ATen returns [2.0] for a
            # constant-2.5 column with bins=0.
            left = left - 0.5
            right = right + 0.5
            if num_edges == 1:
                edges.append(torch.tensor([left], dtype=self.dtype, device=self.device))
                continue

        edges.append(_linspace(left, right, num_edges, self.dtype, self.device))

    edges_tuple = tuple(edges)

    if out is not None:
        # ATen validates the out list before writing: the length must match the
        # number of histogram dimensions, and each output's dtype must equal the
        # input's (it raises rather than casting, so ``copy_`` alone would silently
        # accept an fp64 out for an fp32 input).
        if len(out) != N:
            raise RuntimeError(
                f"_histogramdd_bin_edges: expected out to have {N} tensors, "
                f"got {len(out)}"
            )
        for d in range(N):
            if out[d].dtype != self.dtype:
                raise RuntimeError(
                    f"Expected out tensor to have dtype {self.dtype}, but got "
                    f"{out[d].dtype} instead"
                )
            if out[d].device != self.device:
                raise RuntimeError(
                    f"Expected out tensor to have device {self.device}, but got "
                    f"{out[d].device} instead"
                )
        for d in range(N):
            expected = edges_tuple[d].numel()
            if out[d].numel() != expected:
                # Matches ATen, which resizes a mismatched output in place (and
                # warns when it had elements) rather than rejecting it.
                out[d].resize_(expected)
            out[d].copy_(edges_tuple[d])
        return out

    return edges_tuple


def _histogramdd_bin_edges(self, bins, *, range=None, weight=None, density=False):
    logger.debug("GEMS _HISTOGRAMDD_BIN_EDGES")
    return _histogramdd_bin_edges_impl(
        self, bins, range=range, weight=weight, density=density
    )


def _histogramdd_bin_edges_out(
    self, bins, *, range=None, weight=None, density=False, out=None
):
    logger.debug("GEMS _HISTOGRAMDD_BIN_EDGES_OUT")
    # The ``.out`` overload has a ``-> ()`` schema, so the in-place results are
    # written into ``out`` and the dispatcher expects this entry to return None.
    _histogramdd_bin_edges_impl(
        self, bins, range=range, weight=weight, density=density, out=out
    )
    return None
