# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List

import torch
import triton
import triton.language as tl

from flag_gems import runtime

logger = logging.getLogger(__name__)


@triton.autotune(
    configs=runtime.get_tuned_config("unbind"),
    key=["num_elements"],
)
@triton.jit
def unbind_kernel(
    input_ptr,
    output_ptr,
    dim_size,
    dim_prod_post,
    num_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel for unbind.

    Uses a 2D grid: (num_blocks, dim_size)
    - program_id(0): block index within one output tensor
    - program_id(1): which output tensor (slice) to copy
    """
    pid_x = tl.program_id(0)
    slice_id = tl.program_id(1)

    block_start = pid_x * BLOCK_SIZE
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = block_start + offsets < num_elements

    idx = block_start + offsets

    # Compute indices in the output tensor
    pre_idx = idx // dim_prod_post
    post_idx = idx % dim_prod_post

    # Compute the flat index in the input tensor
    input_flat_idx = (
        pre_idx * dim_size * dim_prod_post + slice_id * dim_prod_post + post_idx
    )

    # Load from input
    data = tl.load(input_ptr + input_flat_idx, mask=mask)

    # Store to output - each slice has its own contiguous storage
    slice_offset = slice_id * num_elements
    tl.store(output_ptr + slice_offset + idx, data, mask=mask)


def unbind(input: torch.Tensor, dim: int = 0) -> List[torch.Tensor]:
    """Remove a tensor dimension.

    Returns a tuple of all slices along a given dimension, already without it.

    Args:
        input: The tensor to unbind
        dim: The dimension to remove

    Returns:
        A tuple of tensors
    """
    logger.debug("GEMS UNBIND")

    if dim < 0:
        dim = dim + input.ndim

    if dim < 0 or dim >= input.ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of "
            f"[{-input.ndim}, {input.ndim - 1}], but got {dim})"
        )

    num_slices = input.shape[dim]
    if num_slices == 0:
        return ()

    # Shape of each output tensor (without the unbind dimension)
    output_shape = list(input.shape)
    del output_shape[dim]

    num_elements_per_slice = 1
    for s in output_shape:
        num_elements_per_slice *= s

    if num_elements_per_slice == 0:
        return tuple(
            torch.empty(output_shape, dtype=input.dtype, device=input.device)
            for _ in range(num_slices)
        )

    # Total storage needed for all slices
    total_elements = num_slices * num_elements_per_slice
    output_storage = torch.empty(
        (total_elements,), dtype=input.dtype, device=input.device
    )

    # Product of dimension sizes after the unbind dimension
    dim_prod_post = 1
    for i in range(dim + 1, input.ndim):
        dim_prod_post *= input.shape[i]

    # Make input contiguous for simpler indexing
    input = input.contiguous()

    grid = lambda meta: (  # noqa: E731
        triton.cdiv(num_elements_per_slice, meta["BLOCK_SIZE"]),
        num_slices,
    )

    unbind_kernel[grid](
        input,
        output_storage,
        num_slices,
        dim_prod_post,
        num_elements_per_slice,
    )

    # Split the storage into individual output tensors
    outputs = []
    for i in range(num_slices):
        start = i * num_elements_per_slice
        end = start + num_elements_per_slice
        outputs.append(output_storage[start:end].reshape(output_shape))

    return tuple(outputs)
